<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Digitalriver Assignment" duration-ms="35091" started-at="2015-09-14T18:47:02Z" finished-at="2015-09-14T18:47:37Z">
    <groups>
    </groups>
    <test name="Simple Test" duration-ms="35091" started-at="2015-09-14T18:47:02Z" finished-at="2015-09-14T18:47:37Z">
      <class name="org.suyog.digitalriver.tests.VerifyPhoneNumberTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="setUp" is-config="true" duration-ms="2678" started-at="2015-09-15T00:17:02Z" finished-at="2015-09-15T00:17:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="checkCountryCodeForNumber()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="checkCountryCodeForNumber" duration-ms="3898" started-at="2015-09-15T00:17:05Z" description="Validates the country code for a phone number." finished-at="2015-09-15T00:17:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkCountryCodeForNumber -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="tearDown" is-config="true" duration-ms="78" started-at="2015-09-15T00:17:09Z" finished-at="2015-09-15T00:17:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="setUp" is-config="true" duration-ms="2027" started-at="2015-09-15T00:17:09Z" finished-at="2015-09-15T00:17:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="checkE164PhoneNumberFormatSatisfication()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="checkE164PhoneNumberFormatSatisfication" duration-ms="3644" started-at="2015-09-15T00:17:11Z" description="Check if the given phone number satisfies the  internationally recognized standard E164 for telephone numbers anywhere in the world." finished-at="2015-09-15T00:17:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkE164PhoneNumberFormatSatisfication -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="tearDown" is-config="true" duration-ms="78" started-at="2015-09-15T00:17:15Z" finished-at="2015-09-15T00:17:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="setUp" is-config="true" duration-ms="1978" started-at="2015-09-15T00:17:15Z" finished-at="2015-09-15T00:17:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="checkIsPossibleNumber()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="checkIsPossibleNumber" duration-ms="3448" started-at="2015-09-15T00:17:17Z" description="Check whether a phone number is a possible number given a number in the form of a string, and the region where the number could be dialed from." finished-at="2015-09-15T00:17:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkIsPossibleNumber -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="tearDown" is-config="true" duration-ms="76" started-at="2015-09-15T00:17:20Z" finished-at="2015-09-15T00:17:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="setUp" is-config="true" duration-ms="2010" started-at="2015-09-15T00:17:20Z" finished-at="2015-09-15T00:17:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="checkIsValidNumber()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="checkIsValidNumber" duration-ms="3633" started-at="2015-09-15T00:17:22Z" description="Tests whether a phone number matches a valid pattern." finished-at="2015-09-15T00:17:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at org.suyog.digitalriver.pageobjects.DRCustomerSupportPage.readNumberAndVerifyIsValidNumber(DRCustomerSupportPage.java:62)
	at org.suyog.digitalriver.tests.VerifyPhoneNumberTests.checkIsValidNumber(VerifyPhoneNumberTests.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkIsValidNumber -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="tearDown" is-config="true" duration-ms="73" started-at="2015-09-15T00:17:26Z" finished-at="2015-09-15T00:17:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="setUp" is-config="true" duration-ms="1958" started-at="2015-09-15T00:17:26Z" finished-at="2015-09-15T00:17:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="checkNumberType()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="checkNumberType" duration-ms="3736" started-at="2015-09-15T00:17:28Z" description="Gets the type of a phone number." finished-at="2015-09-15T00:17:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at org.suyog.digitalriver.pageobjects.DRCustomerSupportPage.readNumberAndVerifyNumberType(DRCustomerSupportPage.java:116)
	at org.suyog.digitalriver.tests.VerifyPhoneNumberTests.checkNumberType(VerifyPhoneNumberTests.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkNumberType -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="tearDown" is-config="true" duration-ms="86" started-at="2015-09-15T00:17:32Z" finished-at="2015-09-15T00:17:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="setUp" is-config="true" duration-ms="2046" started-at="2015-09-15T00:17:32Z" finished-at="2015-09-15T00:17:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="checkOfflineGeocoderLocation()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="checkOfflineGeocoderLocation" duration-ms="3539" started-at="2015-09-15T00:17:34Z" description="Checks the offlibe geocoder location for a phone number." finished-at="2015-09-15T00:17:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Germany] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Germany] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at org.suyog.digitalriver.pageobjects.DRCustomerSupportPage.readNumberAndVerifyOfflineGeocoderLocation(DRCustomerSupportPage.java:96)
	at org.suyog.digitalriver.tests.VerifyPhoneNumberTests.checkOfflineGeocoderLocation(VerifyPhoneNumberTests.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOfflineGeocoderLocation -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.suyog.digitalriver.tests.VerifyPhoneNumberTests@6093dd95]" name="tearDown" is-config="true" duration-ms="82" started-at="2015-09-15T00:17:37Z" finished-at="2015-09-15T00:17:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.suyog.digitalriver.tests.VerifyPhoneNumberTests -->
    </test> <!-- Simple Test -->
  </suite> <!-- Digitalriver Assignment -->
</testng-results>
